swagger: '2.0'
info:
  title: DialUser Management API
  version: 1.0.0
  description: 拨测用户管理API接口
host: localhost:8087
basePath: /dialingtest/api
schemes:
  - https

consumes:
  - "application/json"

produces:
  - "application/json"
paths:
  /dialusers:
    get:
      summary: 分页查询拨测用户
      description: 分页查询拨测用户列表，支持用户名过滤
      parameters:
        - name: page
          in: query
          description: 页码，从0开始
          required: false
          type: integer
          default: 0
        - name: size
          in: query
          description: 每页大小
          required: false
          type: integer
          default: 10
        - name: username
          in: query
          description: 用户名过滤条件
          required: false
          type: string
      responses:
        '200':
          description: 查询成功
          schema:
            $ref: '#/definitions/DialUserPageResponse'
        '401':
          description: 未提供用户名
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/ErrorResponse'
    post:
      summary: 新增拨测用户
      description: 新增拨测用户，仅ADMIN权限的用户有操作权限
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/CreateDialUserRequest'
        - name: "X-Username"
          in: "header"
          required: true
          type: "string"
          description: "操作用户名"
      responses:
        '201':
          description: 创建成功
          schema:
            $ref: '#/definitions/DialUserResponse'
        '400':
          description: 请求参数错误
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: 未提供用户名
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: 权限不足，仅ADMIN用户可操作
          schema:
            $ref: '#/definitions/ErrorResponse'
        '409':
          description: 用户名已存在
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/ErrorResponse'
  /dialusers/{id}:
    get:
      summary: 根据ID查询拨测用户
      description: 根据ID查询拨测用户详情
      parameters:
        - name: id
          in: path
          required: true
          description: 用户ID
          type: integer
      responses:
        '200':
          description: 查询成功
          schema:
            $ref: '#/definitions/DialUserResponse'
        '401':
          description: 未提供用户名
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: 用户不存在
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/ErrorResponse'
    put:
      summary: 修改拨测用户
      description: 修改拨测用户信息，仅ADMIN权限的用户有操作权限
      parameters:
        - name: id
          in: path
          required: true
          description: 用户ID
          type: integer
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/UpdateDialUserRequest'
        - name: "X-Username"
          in: "header"
          required: true
          type: "string"
          description: "操作用户名"
      responses:
        '200':
          description: 修改成功
          schema:
            $ref: '#/definitions/DialUserResponse'
        '400':
          description: 请求参数错误
          schema:
            $ref: '#/definitions/ErrorResponse'
        '401':
          description: 未提供用户名
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: 权限不足，仅ADMIN用户可操作
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: 用户不存在
          schema:
            $ref: '#/definitions/ErrorResponse'
        '409':
          description: 用户名已存在
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      summary: 删除拨测用户
      description: 删除拨测用户，仅ADMIN权限的用户有操作权限
      parameters:
        - name: id
          in: path
          required: true
          description: 用户ID
          type: integer
        - name: "X-Username"
          in: "header"
          required: true
          type: "string"
          description: "操作用户名"
      responses:
        '204':
          description: 删除成功
        '401':
          description: 未提供用户名
          schema:
            $ref: '#/definitions/ErrorResponse'
        '403':
          description: 权限不足，仅ADMIN用户可操作
          schema:
            $ref: '#/definitions/ErrorResponse'
        '404':
          description: 用户不存在
          schema:
            $ref: '#/definitions/ErrorResponse'
        '500':
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  DialUser:
    type: object
    properties:
      id:
        type: integer
        description: 用户ID
      username:
        type: string
        description: 用户名
      password:
        type: string
        description: 密码（加密后）
      lastLoginTime:
        type: string
        description: 最后登录时间
  CreateDialUserRequest:
    type: object
    required:
      - username
      - password
    properties:
      username:
        type: string
        description: 用户名
        maxLength: 50
      password:
        type: string
        description: 密码
        minLength: 6
  UpdateDialUserRequest:
    type: object
    properties:
      username:
        type: string
        description: 用户名
        maxLength: 50
      password:
        type: string
        description: 密码
        minLength: 6
  DialUserResponse:
    type: object
    properties:
      success:
        type: boolean
        description: 操作是否成功
      data:
        $ref: '#/definitions/DialUser'
      message:
        type: string
        description: 响应消息
  DialUserPageResponse:
    type: object
    properties:
      success:
        type: boolean
        description: 操作是否成功
      data:
        type: object
        properties:
          content:
            type: array
            items:
              $ref: '#/definitions/DialUser'
          totalElements:
            type: integer
            description: 总记录数
          totalPages:
            type: integer
            description: 总页数
          size:
            type: integer
            description: 每页大小
          number:
            type: integer
            description: 当前页码
      message:
        type: string
        description: 响应消息

  ErrorResponse:
    type: object
    properties:
      success:
        type: boolean
        description: 请求是否成功
        example: false
      message:
        type: string
        description: 错误消息
        example: "操作失败"
      errorCode:
        type: string
        description: 错误代码
        example: "INVALID_PARAMETER"
