openapi: 3.0.0
info:
  title: "文件上传API"
  description: "文件上传模块的RESTful API接口"
  version: "1.0.0"
  contact:
    name: "拨测控制中心开发团队"
    email: "dev@example.com"

servers:
  - url: "https://localhost:8087/dialingtest/api"
    description: "开发环境"

paths:
  /upload:
    post:
      tags:
        - "文件上传"
      summary: "上传用例集文件"
      description: "上传ZIP或TAR.GZ格式的用例集包，使用HttpServletRequest处理请求"
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: "用例集文件（ZIP或TAR.GZ格式）"
                description:
                  type: string
                  description: "用例集描述信息"
                businessZh:
                  type: string
                  description: "业务类型（中文）"
                businessEn:
                  type: string
                  description: "业务类型（英文）"
                overwrite:
                  type: string
                  description: "是否覆盖已存在的用例集，默认为false"
                  default: "false"
              required:
                - file
      parameters:
        - name: "X-Username"
          in: "header"
          required: true
          schema:
            type: string
          description: "操作用户名"
      responses:
        '200':
          description: "成功上传用例集"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TestCaseSetUploadResponse"
        '400':
          description: "请求参数错误或文件格式错误"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '403':
          description: "权限不足"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        '500':
          description: "服务器内部错误"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    TestCaseSet:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: "用例集ID"
        name:
          type: string
          description: "用例集名称"
          example: "短视频采集"
        version:
          type: string
          description: "用例集版本"
          example: "v0.1"
        fileContent:
          type: string
          format: byte
          description: "文件内容（Base64编码）"
          example: "UEsDBBQAAAAIAA..."
        fileSize:
          type: integer
          format: int64
          description: "文件大小（字节）"
          example: 2621440
        description:
          type: string
          description: "描述信息"
          example: "短视频采集测试用例集"
        sha256:
          type: string
          description: "文件SHA256哈希值"
          example: "a1b2c3d4e5f6..."
        businessZh:
          type: string
          description: "业务类型（中文）"
          example: "VPN阻断"
        businessEn:
          type: string
          description: "业务类型（英文）"
          example: "VPN_BLOCK"

    TestCaseSetUploadResponse:
      type: object
      properties:
        success:
          type: boolean
          description: "请求是否成功"
          example: true
        message:
          type: string
          description: "响应消息"
          example: "上传用例集成功"
        data:
          $ref: "#/components/schemas/TestCaseSet"

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          description: "请求是否成功"
          example: false
        message:
          type: string
          description: "错误消息"
          example: "操作失败"
        errorCode:
          type: string
          description: "错误代码"
          example: "INVALID_PARAMETER"