swagger: '2.0'
info:
  title: User Role Management API
  description: 用户角色管理API接口
  version: 1.0.0
  contact:
    name: DialTestCenter Team
    email: support@dialtestcenter.com

basePath: /dialingtest/api
produces:
  - application/json
consumes:
  - application/json

paths:
  /user-roles:
    get:
      summary: 获取用户角色列表
      description: 支持分页查询和搜索，需要ADMIN或OPERATOR权限
      tags:
        - UserRole
      parameters:
        - name: page
          in: query
          type: integer
          default: 0
          description: 页码，从0开始
        - name: size
          in: query
          type: integer
          default: 10
          description: 每页大小
        - name: search
          in: query
          type: string
          description: 搜索关键词
        - name: X-Username
          in: header
          required: true
          type: string
          description: 操作用户名
      responses:
        200:
          description: 成功返回用户角色列表
          schema:
            $ref: '#/definitions/UserRolePageResponse'
        401:
          description: 未提供用户名
          schema:
            $ref: '#/definitions/ErrorResponse'
        403:
          description: 权限不足
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/ErrorResponse'
            
    post:
      summary: 创建用户角色关系
      description: 创建新的用户角色关系，需要ADMIN权限，自动记录操作日志
      tags:
        - UserRole
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/CreateUserRoleRequest'
        - name: X-Username
          in: header
          required: true
          type: string
          description: 操作用户名
      responses:
        201:
          description: 创建成功
          schema:
            $ref: '#/definitions/UserRoleResponse'
        400:
          description: 请求参数错误
          schema:
            $ref: '#/definitions/ErrorResponse'
        409:
          description: 用户角色关系已存在
          schema:
            $ref: '#/definitions/ErrorResponse'
        403:
          description: 权限不足
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/ErrorResponse'

  /user-roles/{id}:
    put:
      summary: 更新用户角色关系
      description: 更新现有用户角色关系，需要ADMIN权限，自动记录操作日志
      tags:
        - UserRole
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: 用户角色关系ID
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/UpdateUserRoleRequest'
        - name: X-Username
          in: header
          required: true
          type: string
          description: 操作用户名
      responses:
        200:
          description: 更新成功
          schema:
            $ref: '#/definitions/UserRoleResponse'
        404:
          description: 用户角色关系不存在
          schema:
            $ref: '#/definitions/ErrorResponse'
        403:
          description: 权限不足
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/ErrorResponse'
            
    delete:
      summary: 删除用户角色关系
      description: 删除用户角色关系，需要ADMIN权限，自动记录操作日志
      tags:
        - UserRole
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: 用户角色关系ID
        - name: X-Username
          in: header
          required: true
          type: string
          description: 操作用户名
      responses:
        204:
          description: 删除成功
        404:
          description: 用户角色关系不存在
          schema:
            $ref: '#/definitions/ErrorResponse'
        403:
          description: 权限不足
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/ErrorResponse'

  /user-roles/check-permission:
    post:
      summary: 检查用户权限
      description: 检查用户是否具有指定权限，自动记录权限检查日志
      tags:
        - UserRole
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/CheckPermissionRequest'
        - name: X-Username
          in: header
          required: true
          type: string
          description: 操作用户名
      responses:
        200:
          description: 权限检查结果
          schema:
            $ref: '#/definitions/PermissionCheckResponse'
        401:
          description: 未提供用户名
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/ErrorResponse'

  /user-roles/roles:
    get:
      summary: 获取所有角色列表
      description: 获取系统中定义的所有角色
      tags:
        - UserRole
      parameters:
        - name: X-Username
          in: header
          required: true
          type: string
          description: 操作用户名
      responses:
        200:
          description: 成功返回角色列表
          schema:
            type: array
            items:
              $ref: '#/definitions/RoleResponse'
        401:
          description: 未提供用户名
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/ErrorResponse'

definitions:
  UserRole:
    type: object
    properties:
      id:
        type: integer
        description: 主键ID
      username:
        type: string
        description: 用户名
      role:
        type: string
        description: 角色代码
        enum: [ADMIN, OPERATOR, BROWSER, EXECUTOR]
    required:
      - id
      - username
      - role

  UserRoleResponse:
    type: object
    properties:
      success:
        type: boolean
        description: 操作是否成功
      data:
        $ref: '#/definitions/UserRole'
      message:
        type: string
        description: 响应消息
    required:
      - success
      - data
      - message

  UserRolePageResponse:
    type: object
    properties:
      success:
        type: boolean
        description: 操作是否成功
      data:
        type: object
        properties:
          content:
            type: array
            items:
              $ref: '#/definitions/UserRole'
          totalElements:
            type: integer
            description: 总记录数
          totalPages:
            type: integer
            description: 总页数
          size:
            type: integer
            description: 每页大小
          number:
            type: integer
            description: 当前页码
          first:
            type: boolean
            description: 是否第一页
          last:
            type: boolean
            description: 是否最后一页
        required:
          - content
          - totalElements
          - totalPages
          - size
          - number
          - first
          - last
      message:
        type: string
        description: 响应消息
    required:
      - success
      - data
      - message

  CreateUserRoleRequest:
    type: object
    properties:
      username:
        type: string
        description: 目标用户名
      role:
        type: string
        description: 角色类型
        enum: [ADMIN, OPERATOR, BROWSER, EXECUTOR]
    required:
      - username
      - role

  UpdateUserRoleRequest:
    type: object
    properties:
      username:
        type: string
        description: 目标用户名
      role:
        type: string
        description: 角色类型
        enum: [ADMIN, OPERATOR, BROWSER, EXECUTOR]
    required:
      - username
      - role

  CheckPermissionRequest:
    type: object
    properties:
      username:
        type: string
        description: 要检查的用户名
      roles:
        type: array
        items:
          type: string
        description: 要检查的角色列表
    required:
      - username
      - roles

  PermissionCheckResponse:
    type: object
    properties:
      success:
        type: boolean
        description: 操作是否成功
      data:
        type: object
        properties:
          hasPermission:
            type: boolean
            description: 是否有权限
          userRoles:
            type: array
            items:
              type: string
            description: 用户拥有的角色列表
        required:
          - hasPermission
          - userRoles
      message:
        type: string
        description: 响应消息
    required:
      - success
      - data
      - message

  Role:
    type: object
    properties:
      id:
        type: integer
        description: 主键ID
      code:
        type: string
        description: 角色代码
      nameZh:
        type: string
        description: 中文名称
      nameEn:
        type: string
        description: 英文名称
      descriptionZh:
        type: string
        description: 中文描述
      descriptionEn:
        type: string
        description: 英文描述
    required:
      - id
      - code
      - nameZh
      - nameEn

  RoleResponse:
    type: object
    properties:
      success:
        type: boolean
        description: 操作是否成功
      data:
        $ref: '#/definitions/Role'
      message:
        type: string
        description: 响应消息
    required:
      - success
      - data
      - message

  ErrorResponse:
    type: object
    properties:
      success:
        type: boolean
        description: 操作是否成功
        default: false
      message:
        type: string
        description: 错误消息
      errorCode:
        type: string
        description: 错误代码
    required:
      - success
      - message
