swagger: "2.0"
info:
  title: "Software Package Management API"
  description: "软件包管理API文档 - 提供软件包的上传、下载、查询、删除等操作"
  version: "1.0.0"
  contact:
    name: "g00940940"
    email: "g00940940@huawei.com"
host: "localhost:8087"
basePath: "/dialingtest"
schemes:
  - "https"
  - "http"
consumes:
  - "application/json"
  - "multipart/form-data"
produces:
  - "application/json"
  - "application/octet-stream"

paths:
  /api/software-packages:
    get:
      tags:
        - "软件包管理"
      summary: "获取软件包列表"
      description: "获取软件包列表，支持分页和搜索"
      parameters:
        - name: "page"
          in: "query"
          required: false
          type: "integer"
          format: "int32"
          default: 1
          description: "页码（从1开始）"
        - name: "pageSize"
          in: "query"
          required: false
          type: "integer"
          format: "int32"
          default: 10
          description: "每页大小"
        - name: "platform"
          in: "query"
          required: false
          type: "string"
          enum: ["android", "ios"]
          description: "平台过滤"
        - name: "creator"
          in: "query"
          required: false
          type: "string"
          description: "创建者过滤"
        - name: "softwareName"
          in: "query"
          required: false
          type: "string"
          description: "软件名称过滤"
      responses:
        200:
          description: "成功获取软件包列表"
          schema:
            $ref: "#/definitions/ApiResponsePagedSoftwarePackage"
        400:
          description: "请求参数错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"

  /api/software-packages/{id}:
    get:
      tags:
        - "软件包管理"
      summary: "获取软件包详情"
      description: "根据ID获取软件包的详细信息"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          format: "int64"
          description: "软件包ID"
      responses:
        200:
          description: "成功获取软件包详情"
          schema:
            $ref: "#/definitions/ApiResponseSoftwarePackage"
        404:
          description: "软件包不存在"
          schema:
            $ref: "#/definitions/BaseApiResponse"
        400:
          description: "请求参数错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"

    put:
      tags:
        - "软件包管理"
      summary: "更新软件包"
      description: "更新软件包信息"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          format: "int64"
          description: "软件包ID"
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/SoftwarePackageUpdateRequest"
      responses:
        200:
          description: "软件包更新成功"
          schema:
            $ref: "#/definitions/ApiResponseSoftwarePackage"
        400:
          description: "请求参数错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"

    delete:
      tags:
        - "软件包管理"
      summary: "删除软件包"
      description: "删除指定的软件包"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          format: "int64"
          description: "软件包ID"
      responses:
        204:
          description: "软件包删除成功"
        404:
          description: "软件包不存在"
        400:
          description: "请求参数错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"

  /api/software-packages/upload:
    post:
      tags:
        - "软件包管理"
      summary: "上传单个软件包"
      description: "上传新的软件包文件（支持APK和IPA格式）"
      consumes:
        - "multipart/form-data"
      parameters:
        - name: "file"
          in: "formData"
          required: true
          type: "file"
          description: "软件包文件（APK或IPA格式）"
        - name: "description"
          in: "formData"
          required: false
          type: "string"
          description: "软件包描述"
      responses:
        200:
          description: "软件包上传成功"
          schema:
            $ref: "#/definitions/ApiResponseSoftwarePackage"
        400:
          description: "文件格式错误或参数无效"
          schema:
            $ref: "#/definitions/BaseApiResponse"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"

  /api/software-packages/upload-zip:
    post:
      tags:
        - "软件包管理"
      summary: "批量上传软件包"
      description: "批量上传多个软件包文件（ZIP格式）"
      consumes:
        - "multipart/form-data"
      parameters:
        - name: "file"
          in: "formData"
          required: true
          type: "file"
          description: "包含多个软件包的ZIP文件"
      responses:
        200:
          description: "批量上传成功"
          schema:
            $ref: "#/definitions/ApiResponseSoftwarePackageList"
        400:
          description: "文件格式错误或参数无效"
          schema:
            $ref: "#/definitions/BaseApiResponse"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"

  /api/software-packages/{id}/download:
    get:
      tags:
        - "软件包管理"
      summary: "下载软件包文件"
      description: "下载软件包的原始文件"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          format: "int64"
          description: "软件包ID"
      responses:
        200:
          description: "文件下载成功"
          schema:
            type: "file"
        404:
          description: "软件包不存在"
        400:
          description: "请求参数错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"

  /api/software-packages/statistics:
    get:
      tags:
        - "软件包管理"
      summary: "获取软件包统计信息"
      description: "获取各平台软件包数量的统计信息"
      responses:
        200:
          description: "成功获取统计信息"
          schema:
            $ref: "#/definitions/ApiResponseStatistics"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"

definitions:
  SoftwarePackage:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "软件包ID"
      softwareName:
        type: "string"
        description: "软件名称"
      fileName:
        type: "string"
        description: "文件名"
      fileFormat:
        type: "string"
        enum: ["apk", "ipa"]
        description: "文件格式"
      platform:
        type: "string"
        enum: ["android", "ios"]
        description: "平台"
      creator:
        type: "string"
        description: "创建者"
      fileSize:
        type: "integer"
        format: "int64"
        description: "文件大小（字节）"
      description:
        type: "string"
        description: "描述信息"
      version:
        type: "string"
        description: "软件版本"
      uploadTime:
        type: "string"
        format: "date-time"
        description: "上传时间"

  SoftwarePackageUpdateRequest:
    type: "object"
    properties:
      softwareName:
        type: "string"
        description: "软件名称"
      description:
        type: "string"
        description: "描述信息"

  PagedResponse:
    type: "object"
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/SoftwarePackage"
        description: "数据列表"
      total:
        type: "integer"
        format: "int64"
        description: "总元素数"
      page:
        type: "integer"
        format: "int32"
        description: "当前页码"
      pageSize:
        type: "integer"
        format: "int32"
        description: "每页大小"
      totalPages:
        type: "integer"
        format: "int32"
        description: "总页数"
      hasNext:
        type: "boolean"
        description: "是否有下一页"
      hasPrevious:
        type: "boolean"
        description: "是否有上一页"

  BaseApiResponse:
    type: "object"
    properties:
      success:
        type: "boolean"
        description: "操作是否成功"
      data:
        type: "object"
        description: "响应数据"
      message:
        type: "string"
        description: "响应消息"
      errorCode:
        type: "string"
        description: "错误代码"

  ApiResponseSoftwarePackage:
    allOf:
      - $ref: "#/definitions/BaseApiResponse"
      - type: "object"
        properties:
          data:
            $ref: "#/definitions/SoftwarePackage"

  ApiResponseSoftwarePackageList:
    allOf:
      - $ref: "#/definitions/BaseApiResponse"
      - type: "object"
        properties:
          data:
            type: "array"
            items:
              $ref: "#/definitions/SoftwarePackage"

  ApiResponsePagedSoftwarePackage:
    allOf:
      - $ref: "#/definitions/BaseApiResponse"
      - type: "object"
        properties:
          data:
            $ref: "#/definitions/PagedResponse"

  ApiResponseStatistics:
    allOf:
      - $ref: "#/definitions/BaseApiResponse"
      - type: "object"
        properties:
          data:
            type: "object"
            additionalProperties:
              type: "integer"
              format: "int64"
            description: "平台统计信息，键为平台名称，值为数量"