swagger: "2.0"
info:
  title: "Test Case Set Management API"
  description: "测试用例集管理API文档 - 提供测试用例集的上传、下载、查询、删除等操作"
  version: "1.0.0"
  contact:
    name: "g00940940"
    email: "g00940940@huawei.com"
host: "localhost:8087"
basePath: "/dialingtest"
schemes:
  - "https"
  - "http"
consumes:
  - "application/json"
  - "multipart/form-data"
produces:
  - "application/json"
  - "application/octet-stream"

paths:
  /api/test-case-sets:
    get:
      tags:
        - "测试用例集管理"
      summary: "获取测试用例集列表"
      description: "获取测试用例集列表，支持分页"
      parameters:
        - name: "page"
          in: "query"
          required: false
          type: "integer"
          format: "int32"
          default: 1
          description: "页码（从1开始）"
        - name: "pageSize"
          in: "query"
          required: false
          type: "integer"
          format: "int32"
          default: 10
          description: "每页大小"
      responses:
        200:
          description: "成功获取测试用例集列表"
          schema:
            $ref: "#/definitions/ApiResponsePagedTestCaseSet"
        400:
          description: "请求参数错误"
          schema:
            $ref: "#/definitions/ApiResponseError"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/ApiResponseError"

  /api/test-case-sets/{id}:
    get:
      tags:
        - "测试用例集管理"
      summary: "获取测试用例集详情"
      description: "根据ID获取测试用例集的详细信息"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          format: "int64"
          description: "测试用例集ID"
      responses:
        200:
          description: "成功获取测试用例集详情"
          schema:
            $ref: "#/definitions/ApiResponseTestCaseSet"
        404:
          description: "测试用例集不存在"
          schema:
            $ref: "#/definitions/ApiResponseError"
        400:
          description: "请求参数错误"
          schema:
            $ref: "#/definitions/ApiResponseError"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/ApiResponseError"

    put:
      tags:
        - "测试用例集管理"
      summary: "更新测试用例集"
      description: "更新测试用例集信息"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          format: "int64"
          description: "测试用例集ID"
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/TestCaseSetUpdateRequest"
      responses:
        200:
          description: "测试用例集更新成功"
          schema:
            $ref: "#/definitions/ApiResponseTestCaseSet"
        400:
          description: "请求参数错误"
          schema:
            $ref: "#/definitions/ApiResponseError"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/ApiResponseError"

    delete:
      tags:
        - "测试用例集管理"
      summary: "删除测试用例集"
      description: "删除指定的测试用例集"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          format: "int64"
          description: "测试用例集ID"
      responses:
        204:
          description: "测试用例集删除成功"
        404:
          description: "测试用例集不存在"
        400:
          description: "请求参数错误"
          schema:
            $ref: "#/definitions/ApiResponseError"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/ApiResponseError"

  /api/test-case-sets/upload:
    post:
      tags:
        - "测试用例集管理"
      summary: "上传测试用例集"
      description: "上传新的测试用例集文件（支持ZIP和TAR.GZ格式）"
      consumes:
        - "multipart/form-data"
      parameters:
        - name: "file"
          in: "formData"
          required: true
          type: "file"
          description: "测试用例集文件（ZIP或TAR.GZ格式）"
        - name: "description"
          in: "formData"
          required: false
          type: "string"
          description: "用例集描述"
        - name: "business"
          in: "formData"
          required: false
          type: "string"
          default: "VPN阻断业务"
          description: "业务类型"
      responses:
        200:
          description: "测试用例集上传成功"
          schema:
            $ref: "#/definitions/ApiResponseTestCaseSet"
        400:
          description: "文件格式错误或参数无效"
          schema:
            $ref: "#/definitions/ApiResponseError"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/ApiResponseError"

  /api/test-case-sets/{id}/download:
    get:
      tags:
        - "测试用例集管理"
      summary: "下载测试用例集文件"
      description: "下载测试用例集的原始文件"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          format: "int64"
          description: "测试用例集ID"
      responses:
        200:
          description: "文件下载成功"
          schema:
            type: "file"
        404:
          description: "测试用例集不存在"
        400:
          description: "请求参数错误"
          schema:
            $ref: "#/definitions/ApiResponseError"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/ApiResponseError"

  /api/test-case-sets/{id}/test-cases:
    get:
      tags:
        - "测试用例管理"
      summary: "获取测试用例列表"
      description: "获取指定测试用例集下的所有测试用例"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          format: "int64"
          description: "测试用例集ID"
        - name: "page"
          in: "query"
          required: false
          type: "integer"
          format: "int32"
          default: 1
          description: "页码（从1开始）"
        - name: "pageSize"
          in: "query"
          required: false
          type: "integer"
          format: "int32"
          default: 10
          description: "每页大小"
      responses:
        200:
          description: "成功获取测试用例列表"
          schema:
            $ref: "#/definitions/ApiResponsePagedTestCase"
        404:
          description: "测试用例集不存在"
          schema:
            $ref: "#/definitions/ApiResponseError"
        400:
          description: "请求参数错误"
          schema:
            $ref: "#/definitions/ApiResponseError"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/ApiResponseError"

  /api/test-case-sets/{id}/missing-scripts:
    get:
      tags:
        - "测试用例管理"
      summary: "获取缺少脚本的测试用例"
      description: "获取指定测试用例集中缺少脚本的测试用例列表"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          format: "int64"
          description: "测试用例集ID"
      responses:
        200:
          description: "成功获取缺少脚本的测试用例列表"
          schema:
            $ref: "#/definitions/ApiResponseMissingScripts"
        404:
          description: "测试用例集不存在"
          schema:
            $ref: "#/definitions/ApiResponseError"
        400:
          description: "请求参数错误"
          schema:
            $ref: "#/definitions/ApiResponseError"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/ApiResponseError"

definitions:
  TestCaseSet:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "测试用例集ID"
      name:
        type: "string"
        description: "用例集名称"
      version:
        type: "string"
        description: "用例集版本"
      fileFormat:
        type: "string"
        enum: ["zip", "tar.gz"]
        description: "文件格式"
      business:
        type: "string"
        description: "业务类型"
      creator:
        type: "string"
        description: "创建人"
      fileSize:
        type: "integer"
        format: "int64"
        description: "文件大小（字节）"
      description:
        type: "string"
        description: "描述"
      uploadTime:
        type: "string"
        format: "date-time"
        description: "上传时间"

  TestCase:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "测试用例ID"
      testCaseSetId:
        type: "integer"
        format: "int64"
        description: "关联的用例集ID"
      caseName:
        type: "string"
        description: "用例名称"
      caseNumber:
        type: "string"
        description: "用例编号"
      networkTopology:
        type: "string"
        description: "逻辑组网"
      businessCategory:
        type: "string"
        description: "业务大类"
      app:
        type: "string"
        description: "用例App"
      testSteps:
        type: "string"
        description: "测试步骤"
      expectedResult:
        type: "string"
        description: "预期结果"
      scriptExists:
        type: "boolean"
        description: "脚本是否存在"

  TestCaseSetUpdateRequest:
    type: "object"
    properties:
      name:
        type: "string"
        description: "用例集名称"
      version:
        type: "string"
        description: "用例集版本"
      description:
        type: "string"
        description: "描述"

  PagedResponse:
    type: "object"
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/TestCaseSet"
        description: "数据列表"
      total:
        type: "integer"
        format: "int64"
        description: "总元素数"
      page:
        type: "integer"
        format: "int32"
        description: "当前页码"
      pageSize:
        type: "integer"
        format: "int32"
        description: "每页大小"
      totalPages:
        type: "integer"
        format: "int32"
        description: "总页数"
      hasNext:
        type: "boolean"
        description: "是否有下一页"
      hasPrevious:
        type: "boolean"
        description: "是否有上一页"

  PagedTestCaseResponse:
    type: "object"
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/TestCase"
        description: "数据列表"
      total:
        type: "integer"
        format: "int64"
        description: "总元素数"
      page:
        type: "integer"
        format: "int32"
        description: "当前页码"
      pageSize:
        type: "integer"
        format: "int32"
        description: "每页大小"
      totalPages:
        type: "integer"
        format: "int32"
        description: "总页数"
      hasNext:
        type: "boolean"
        description: "是否有下一页"
      hasPrevious:
        type: "boolean"
        description: "是否有上一页"

  MissingScriptsResponse:
    type: "object"
    properties:
      testCases:
        type: "array"
        items:
          $ref: "#/definitions/TestCase"
        description: "缺少脚本的测试用例列表"
      count:
        type: "integer"
        format: "int64"
        description: "缺少脚本的测试用例数量"

  ApiResponse:
    type: "object"
    properties:
      success:
        type: "boolean"
        description: "操作是否成功"
      data:
        type: "object"
        description: "响应数据"
      message:
        type: "string"
        description: "响应消息"
      timestamp:
        type: "string"
        format: "date-time"
        description: "响应时间戳"
      errorCode:
        type: "string"
        description: "错误代码"

  ApiResponseTestCaseSet:
    allOf:
      - $ref: "#/definitions/ApiResponse"
      - type: "object"
        properties:
          data:
            $ref: "#/definitions/TestCaseSet"

  ApiResponsePagedTestCaseSet:
    allOf:
      - $ref: "#/definitions/ApiResponse"
      - type: "object"
        properties:
          data:
            $ref: "#/definitions/PagedResponse"

  ApiResponsePagedTestCase:
    allOf:
      - $ref: "#/definitions/ApiResponse"
      - type: "object"
        properties:
          data:
            $ref: "#/definitions/PagedTestCaseResponse"

  ApiResponseMissingScripts:
    allOf:
      - $ref: "#/definitions/ApiResponse"
      - type: "object"
        properties:
          data:
            $ref: "#/definitions/MissingScriptsResponse"

  ApiResponseError:
    allOf:
      - $ref: "#/definitions/ApiResponse"
      - type: "object"
        properties:
          success:
            type: "boolean"
            example: false
          data:
            type: "null"
          errorCode:
            type: "string"
            description: "错误代码"
            example: "VALIDATION_ERROR"