swagger: "2.0"
info:
  title: "User Management API"
  description: "用户管理API文档 - 提供用户的创建、更新、删除、查询等操作"
  version: "1.0.0"
  contact:
    name: "g00940940"
    email: "g00940940@huawei.com"
host: "localhost:8087"
basePath: "/dialingtest"
schemes:
  - "https"
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /api/users:
    get:
      tags:
        - "用户管理"
      summary: "获取用户列表（分页）"
      description: "获取用户列表，支持分页和搜索功能"
      parameters:
        - name: "page"
          in: "query"
          description: "页码，从1开始"
          required: false
          type: "integer"
          default: 1
          minimum: 1
        - name: "pageSize"
          in: "query"
          description: "每页大小"
          required: false
          type: "integer"
          default: 10
          minimum: 1
          maximum: 100
        - name: "search"
          in: "query"
          description: "搜索关键字（用户名）"
          required: false
          type: "string"
      responses:
        200:
          description: "成功获取用户列表"
          schema:
            $ref: "#/definitions/UserListResponse"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"
    post:
      tags:
        - "用户管理"
      summary: "创建新用户"
      description: "创建新的用户账号"
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/UserCreateRequest"
      responses:
        201:
          description: "用户创建成功"
          schema:
            $ref: "#/definitions/UserResponse"
        400:
          description: "请求参数错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"

  /api/users/{id}:
    put:
      tags:
        - "用户管理"
      summary: "更新用户信息"
      description: "更新指定用户的信息"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          format: "int64"
          description: "用户ID"
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/UserUpdateRequest"
      responses:
        200:
          description: "用户更新成功"
          schema:
            $ref: "#/definitions/UserResponse"
        400:
          description: "请求参数错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"
    delete:
      tags:
        - "用户管理"
      summary: "删除用户"
      description: "删除指定的用户"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          format: "int64"
          description: "用户ID"
      responses:
        200:
          description: "用户删除成功"
          schema:
            $ref: "#/definitions/MessageResponse"
        400:
          description: "请求参数错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/BaseApiResponse"





definitions:
  BaseApiResponse:
    type: "object"
    properties:
      success:
        type: "boolean"
        description: "操作是否成功"
      data:
        description: "响应数据"
      message:
        type: "string"
        description: "操作结果消息"
      errorCode:
        type: "string"
        description: "错误代码（仅在失败时存在）"

  PagedResponse:
    type: "object"
    properties:
      data:
        type: "array"
        description: "分页数据"
        items:
          $ref: "#/definitions/DialUser"
      total:
        type: "integer"
        format: "int64"
        description: "总记录数"
      page:
        type: "integer"
        description: "当前页码"
      pageSize:
        type: "integer"
        description: "每页大小"
      totalPages:
        type: "integer"
        description: "总页数"
      hasNext:
        type: "boolean"
        description: "是否有下一页"
      hasPrevious:
        type: "boolean"
        description: "是否有上一页"

  UserListResponse:
    allOf:
      - $ref: "#/definitions/BaseApiResponse"
      - type: "object"
        properties:
          data:
            $ref: "#/definitions/PagedResponse"

  UserResponse:
    allOf:
      - $ref: "#/definitions/BaseApiResponse"
      - type: "object"
        properties:
          data:
            $ref: "#/definitions/DialUser"

  MessageResponse:
    allOf:
      - $ref: "#/definitions/BaseApiResponse"
      - type: "object"
        properties:
          data:
            type: "string"
            description: "成功消息"



  DialUser:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "用户ID"
      username:
        type: "string"
        description: "用户名"
      password:
        type: "string"
        description: "密码（加密存储）"
      lastLoginTime:
        type: "string"
        description: "最后登录时间（格式：yyyy-MM-dd HH:mm:ss）"

  UserCreateRequest:
    type: "object"
    required:
      - "username"
      - "password"
    properties:
      username:
        type: "string"
        description: "用户名"
      password:
        type: "string"
        description: "密码"

  UserUpdateRequest:
    type: "object"
    properties:
      username:
        type: "string"
        description: "用户名"
      password:
        type: "string"
        description: "密码"


