swagger: "2.0"
info:
  title: "User Role Management API"
  description: "用户角色管理API文档 - 提供用户角色的创建、更新、删除、查询等操作"
  version: "1.0.0"
  contact:
    name: "g00940940"
    email: "g00940940@huawei.com"
host: "localhost:8087"
basePath: "/dialingtest"
schemes:
  - "https"
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /api/user-roles:
    get:
      tags:
        - "用户角色管理"
      summary: "获取用户角色列表（分页）"
      description: "获取用户角色关系列表，支持分页和搜索功能"
      parameters:
        - name: "page"
          in: "query"
          description: "页码，从1开始"
          required: false
          type: "integer"
          default: 1
          minimum: 1
        - name: "pageSize"
          in: "query"
          description: "每页大小"
          required: false
          type: "integer"
          default: 10
          minimum: 1
          maximum: 100
        - name: "search"
          in: "query"
          description: "搜索关键字（用户名）"
          required: false
          type: "string"
      responses:
        200:
          description: "成功获取用户角色列表"
          schema:
            $ref: "#/definitions/PagedUserRoleResponse"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      tags:
        - "用户角色管理"
      summary: "创建用户角色"
      description: "为用户分配角色"
      parameters:
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/UserRoleRequest"
      responses:
        201:
          description: "用户角色创建成功"
          schema:
            $ref: "#/definitions/UserRole"
        400:
          description: "请求参数错误"
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/ErrorResponse"

  /api/user-roles/{id}:
    put:
      tags:
        - "用户角色管理"
      summary: "更新用户角色"
      description: "更新用户角色信息"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          format: "int64"
          description: "用户角色ID"
        - name: "body"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/UserRoleRequest"
      responses:
        200:
          description: "用户角色更新成功"
          schema:
            $ref: "#/definitions/UserRole"
        400:
          description: "请求参数错误"
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      tags:
        - "用户角色管理"
      summary: "删除用户角色"
      description: "删除用户角色关系"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "integer"
          format: "int64"
          description: "用户角色ID"
      responses:
        200:
          description: "用户角色删除成功"
          schema:
            $ref: "#/definitions/SuccessResponse"
        400:
          description: "请求参数错误"
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/ErrorResponse"

  /api/user-roles/executor-count:
    get:
      tags:
        - "用户角色管理"
      summary: "获取执行机用户数量"
      description: "统计具有执行机角色的用户数量"
      responses:
        200:
          description: "成功获取执行机用户数量"
          schema:
            $ref: "#/definitions/ExecutorCountResponse"
        500:
          description: "服务器内部错误"
          schema:
            $ref: "#/definitions/ErrorResponse"

definitions:
  PagedUserRoleResponse:
    type: "object"
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/UserRole"
      total:
        type: "integer"
        description: "总记录数"
      page:
        type: "integer"
        description: "当前页码"
      pageSize:
        type: "integer"
        description: "每页大小"
      totalPages:
        type: "integer"
        description: "总页数"

  UserRole:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "用户角色ID"
      username:
        type: "string"
        description: "用户名"
      role:
        type: "string"
        enum: ["ADMIN", "OPERATOR", "BROWSER", "EXECUTOR"]
        description: "角色类型"

  UserRoleRequest:
    type: "object"
    required:
      - "username"
      - "role"
    properties:
      username:
        type: "string"
        description: "用户名"
      role:
        type: "string"
        enum: ["ADMIN", "OPERATOR", "BROWSER", "EXECUTOR"]
        description: "角色类型"

  ExecutorCountResponse:
    type: "object"
    properties:
      count:
        type: "integer"
        format: "int32"
        description: "执行机用户数量"

  SuccessResponse:
    type: "object"
    properties:
      success:
        type: "boolean"
        description: "操作是否成功"
      message:
        type: "string"
        description: "操作结果消息"

  ErrorResponse:
    type: "object"
    properties:
      success:
        type: "boolean"
        description: "操作是否成功"
      error:
        type: "string"
        description: "错误代码"
      message:
        type: "string"
        description: "错误消息"
