# 服务器配置
server:
  port: 8087
  servlet:
    context-path: /dialingtest
  # HTTPS配置
  ssl:
    enabled: true
    key-store: classpath:ssl/keystore.p12
    key-store-password: dialtest123
    key-store-type: PKCS12
    key-alias: dialtestcenter
    key-password: dialtest123
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3
    ciphers: TLS_AES_256_GCM_SHA384,TLS_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

# 跨域配置
spring:
  application:
    name: dial-test-center
    version: 1.0.0
  
  # 数据库配置 - PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/dialingtest
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    # 数据库连接池配置
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # 数据库初始化配置
  sql:
    init:
      mode: always
      continue-on-error: true
  
  # 开发工具
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  
  # 跨域配置
  web:
    cors:
      allowed-origins: "https://localhost:3000,https://localhost:5173,https://localhost:4396,http://localhost:3000,http://localhost:5173,http://localhost:4396"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
logging.config: classpath:config/log4j2-spring.xml